### PR TITLE
Support for codec profiles

### PR DESCRIPTION
**Pull request by davidplowman**
Allows the H264 hardware codec profiles to be changed.

A 2nd commit also bumps the version number in preparation for posting an updated release.

### CODE REVIEW

**Comment by davidplowman** [comment]
@grega Hi Greg, just wondering if someone over at the Foundation is still looking after this repository now that we no longer have Chris? Updates don't come along too often, but I do seem to have needed one just now. Thanks!

**Comment by grega** [comment]
@davidplowman No problem, taking a look now!

**Review by grega — APPROVED** [review]

**Comment by grega** [comment]
Published: https://pypi.org/project/v4l2-python3/0.3.3/

**Comment by davidplowman** [comment]
Great, thanks!

**Pull request merged**
