### PR TITLE
Fix the value of V4L2_MPEG_VIDEO_H264_PROFILE_HIGH

### PR DESCRIPTION
**Pull request by davidplowman**
It should have the value 4, not 3 (which should be EXTENDED profile).

Also bump version to 0.3.5.

### CODE REVIEW

**Comment by davidplowman** [comment]
@grega Hi Greg, would you be able to look over and merge this one? It's just correcting a straight typo/blunder. I've also bumped the version number so that we can make up a new package and roll it out. Thanks!!

**Review by grega — APPROVED** [review]

**Comment by grega** [comment]
@davidplowman thanks! I'll get a new release published this afternoon...

**Comment by grega** [comment]
released 👍 https://pypi.org/project/v4l2-python3/0.3.5/

**Comment by davidplowman** [comment]
@grega Great, thanks!

**Pull request merged**
